### ISSUE TITLE
Ethereum explorer:listen EADDRINUSE 127.0.0.1:8000

### ISSUE THREAD

**Issue by zhuangjinxin** [zhuangjinxin/issues#17]
```
➜  npm start

> EthereumExplorer@0.1.0 prestart /Users/zhuangjinxin/Projects/Ethereum/explorer
> npm install


> EthereumExplorer@0.1.0 postinstall /Users/zhuangjinxin/Projects/Ethereum/explorer
> bower install

up to date in 3.545s

> EthereumExplorer@0.1.0 start /Users/zhuangjinxin/Projects/Ethereum/explorer
> http-server ./app -a localhost -p 8000 -c-1

events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1535:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EthereumExplorer@0.1.0 start: `http-server ./app -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EthereumExplorer@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhuangjinxin/.npm/_logs/2017-12-22T02_03_02_250Z-debug.lo
```

**Comment by zhuangjinxin** [comment]
启动的位置不对，不能正确加载文件；
进入explorer所在的目录，执行`npm start`

注：项目地址`https://github.com/etherparty/explorer`
