### ISSUE TITLE
Geth使用遇到的问题

### ISSUE THREAD

**Issue by zhuangjinxin** [zhuangjinxin/issues#18]
解锁账户：
```
> personal.unlockAccount("0x15f90c4913e23ba3d8e3688050c52d8e6b809b1d", "zhuangjinxin", duration)INFO [12-22|10:43:40] Imported new block receipts

ReferenceError: 'duration' is not defined
    at <anonymous>:1:86
```
正确写法：
```
> personal.unlockAccount("0x15f90c4913e23ba3d8e3688050c52d8e6b809b1d", "zhuangjinxin", 300000)
true
```
注：duration 表示解锁的时间

统一格式：
```
> personal.unlockAccount(账户地址, 密码,解锁时长)
```

**Comment by zhuangjinxin** [comment]
交易失败，gas不足：
```
> eth.sendTransaction({from: '0x15f90c4913e23ba3d8e3688050c52d8e6b809b1d', to: '0xe6bfa1cf67b258162309b119f888ab737ddc94ed', value: web3.toWei(0.01, "ether")})

Error: exceeds block gas limit
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

```

**Comment by zhuangjinxin** [comment]
账号命名：
```
> zhuangjinxin0=eth.accounts[0]
"0x15f90c4913e23ba3d8e3688050c52d8e6b809b1d"
```
```
> zhuangjinxin1=eth.accounts
"0xe6bfa1cf67b258162309b119f888ab737ddc94ed"
```

获取余额：eth.getBalance(zhuangjinxin0)

**Comment by zhuangjinxin** [comment]
开始挖矿:
```
> miner.start()
true
```
停止挖矿:
```
> miner.stop()
true
```
